### ISSUE TITLE
Feature request: show on all monitors with Dash to Panel

### ISSUE THREAD

**Issue by road2react** [fthx/power-profile#2]
Right now, only the default icons are shown (internet, sound, battery), and power profile is only shown on the primary monitor. This is since vanilla gnome assumes that the top bar only appears on one monitor. Is it possible to show the power profile indicator on all monitors?

**Comment by fthx** [comment]
Sorry I forgot to answer this!
I don't know how is made the DtP panel. Maybe this problem is on DtP side, having to pick extra indicators from statusArea's native GS panel?
